### ISSUE TITLE
It's just so nice to see this module

### ISSUE THREAD

**Issue by cqcn1991** [scls19fr/windrose#12]
No issue reported here, just want to say thank you, since there is no places for `discussion`.
I'm just wondering what field are you guys in? My field is Civil Engineering, and our main focus is on the wind effect on buildings, so the wind speed is an essential part for us.

**Comment by scls19fr** [comment]
Hi @cqcn1991,

can you send me an email
https://github.com/scls19fr/

thanks

**Comment by ocefpaf** [comment]
:+1: 

I used to copy `windrose.py` everywhere and/or to copy the code inside packages that I needed.  It is awesome to see this packaged

FYI I just create a conda package for it:

https://github.com/ioos/conda-recipes/pull/420/files

**Comment by scls19fr** [comment]
Thanks. I never did a conda package.

**Comment by cqcn1991** [comment]
@ocefpaf Packages for Anaconda, that's very interesting. I have a problem of managing and sharing environment for `Ipython Notebook`(http://stackoverflow.com/questions/34169781/scipy-ipython-notebook-package-mangement-tool), maybe that would help.

**Comment by scls19fr** [comment]
It will be so nice to see other people contributing to this module ;-)
 https://github.com/scls19fr/windrose/issues
