### ISSUE TITLE
Windrose legend typo

### ISSUE THREAD

**Issue by cosstas** [scls19fr/windrose#13]
First of all thank you for this useful tool.

I have noticed a typo error in line 170 in windrose.py. There is an open bracket "[" at the end of wind speed range instead of "]".
See attached image for the error:

![windrose_893_221](https://cloud.githubusercontent.com/assets/15102684/10449780/73d2eed8-719e-11e5-8cb4-1a3f148dd73b.png)

**Comment by scls19fr** [comment]
it's not a typo

    [0.1 : 1.0[

means 

    0.1 <= speed < 1.0

and

    [1.0 : 1.9[

means 

    1.0 <= speed < 1.9

it shouldn't be `[0.1 : 1.0]` because for wind speed of 1.0 m/s there will be 2 colors.

**Comment by cosstas** [comment]
I see, thank you for the clarification!
