### ISSUE TITLE
Allow for specifying `rmax` to plot

### ISSUE THREAD

**Issue by akrherz** [scls19fr/windrose#14]
When generating lots of windrose plots for timelapses or comparisons, it is useful to have stable polar maximum radius set.  Would you consider an addition of allowing the max radius to be specified instead of dynamically computed from the data?  thanks

**Comment by scls19fr** [comment]
Yes. Nice suggestion. I'm quite busy these days but I'm open to pull requests.

**Comment by scls19fr** [comment]
Last dev version now support rmax parameter.

There is no PyPi version for now but you can install it using

    pip install git+https://github.com/scls19fr/windrose.git

or 

    git clone https://github.com/scls19fr/windrose.git
    python setup.py install

Feel free to reopen an issue is case of problem
