### ISSUE TITLE
ValueError: radial grids must be strictly positive 

### ISSUE THREAD

**Issue by slharris** [scls19fr/windrose#15]
I am having issues with windrose when receiving this error:

    ValueError: radial grids must be strictly positive 

Is there an example of a work around that I can follow as I don't understand what is causing it. My data does not appear to have any negative values (if that is what the error means)?

Any feedback will be greatly appreciated.

**Comment by scls19fr** [comment]
Hi,

without a minimal example I can't help.

Feel free to provide one.

Kind regards

**Comment by scls19fr** [comment]
`rmax` parameter can be passed to `WindroseAxes`. So you can specify any (positive) value.
