### ISSUE TITLE
where is API?

### ISSUE THREAD

**Issue by yeyuguo** [scls19fr/windrose#18]
Can you provide an API for  windrose?I need help with the API.Thanks.

**Comment by yeyuguo** [comment]
I will always be waiting for windrose API,ths!!

**Comment by scls19fr** [comment]
There is no API doc for now. Code is doc ;-)
You can also have a look at samples directory.

**Comment by yeyuguo** [comment]
I can not understand the code, I want to set colorbar like this, can you help me please 
http://matplotlib.org/examples/api/colorbar_only.html    (the first graph)

**Comment by yeyuguo** [comment]
please please please please please please

**Comment by scls19fr** [comment]
Give a man a fish and he will eat for a day; teach a man to fish and he will eat for a lifetime

Have a look at `cmap`.

see

    def _init_plot(self, direction, var, **kwargs):
        ...
       cmap = kwargs.pop('cmap', None)
       ....

so now see when `_init_plot` is called !

You just nee to pass a cmap parameter to coutourf or whatever function you are using.
