### ISSUE TITLE
Seamless Subplotting

### ISSUE THREAD

**Issue by adityasinghwa** [scls19fr/windrose#20]
Hi! I was trying to use the module to plot a bunch of other weather parameters. The module can only be used for standalone plots. I cannot subplot it within my existing plot setup. I have tried some of the work arounds given but was not successful.

**Comment by scls19fr** [comment]
Did you try passing `ax` parameter ?

**Comment by adityasinghwa** [comment]
I did try it. Can you possibly give a sample syntax. My other subplots go something like this:

ax = plt.subplot(514)    
ax.set_ylabel('Cloud Cover (fraction)')
ax.spines["top"].set_visible(False)  
ax.spines["bottom"].set_visible(True)  
ax.spines["right"].set_visible(False)  
ax.spines["left"].set_visible(True) 
ax.get_xaxis().tick_bottom()  
ax.get_yaxis().tick_left()
ax.xaxis.set_major_locator(matplotlib.dates.MonthLocator(bymonth=None, bymonthday=01, interval=4, tz=None))
ax.xaxis.set_major_formatter(matplotlib.dates.DateFormatter('%b %Y'))
line = plt.plot(Date, df.CC, lw=1.5, color='black')
line = plt.plot(Date, movingaverage(df.CC,24), lw=1.0, color='red')

So I need a setup to plot it in position 515.

**Comment by scls19fr** [comment]
I faced a similar issue
see https://github.com/scls19fr/windrose/issues/10
but I never had time to fix it.
Feel free to help by submitting a PR

**Comment by scls19fr** [comment]
It will be great if some Matplotlib experts such as @tacaswell  @JanSchulz or @mdboom (or some others ) could help on this.

**Comment by JanSchulz** [comment]
@adityasinghwa can you post a minimal example which goes wrong?

**Comment by LionelR** [comment]
You have to manually set your WindRoseAxes position on the figure, like you have to do with Axes and PolarAxes, because plt.subplot is just a helper function for that. You can achieve that like this 
```python
from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np
ws = np.random.random(500) * 6
wd = np.random.random(500) * 360
ax=plt.subplot(221) # and set whatever you want in this axes
fig=gcf()
rect=[0.6,0.6,0.3,0.3] # have to be calculated with the others axes
wa=WindroseAxes(fig, rect)
fig.add_axes(wa)
wa.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
```
![figure_1](https://cloud.githubusercontent.com/assets/490118/12814140/100d7e60-cb3d-11e5-9dfc-0b6405c6caa7.png)

**Comment by scls19fr** [comment]
Hi folks,

An subplots example is available at  https://github.com/scls19fr/windrose/blob/master/samples/example_subplots.py

See screeshot

![capture d ecran 2016-02-04 a 14 20 53](https://cloud.githubusercontent.com/assets/109167/12816096/c045c23a-cb4a-11e5-8573-76f0fdd7f85b.png)

This figure is composed of 12 windrose plots from Poitiers (year 2014, monthly)

It can probably be improved to display month (name or number) as subplots title
Adding margin, spacing might also be considered.

We should also provide a better API to make automatically this kind of plot.

Kind regards

**Comment by adityasinghwa** [comment]
![image](https://cloud.githubusercontent.com/assets/16873861/12833819/e7e36ee2-cbee-11e5-8ebf-ca0435b1d0a4.png)

Made this one with matlab where plot_windrose.m integrates seamlessly with normal plotting functions inside matlab. It has a analogue to matplotlib's axes_grid functionality which has been used for this plot.

Will give manually trying to fit the axes a go. The problem is then they have to be manually setup for all the plots.

**Comment by crazy449** [comment]
@adityasinghwa can you share a snippet of your code I am trying to do subplots with other charts like you too but I can't work it out

**Comment by scls19fr** [comment]
Maybe this https://github.com/scls19fr/windrose/issues/38 could help to have easier subplotting.

**Comment by scls19fr** [comment]
`WindroseAxes` is now a registered projection (as `windrose`)

we can do

```
ax1 = fig.add_subplot(131, projection='polar')
ax2 = fig.add_subplot(132, projection='rectilinear')
ax3 = fig.add_subplot(133, projection='windrose')
ax3.bar(dir, vals)
```

an other example can be found

https://github.com/scls19fr/windrose/blob/master/samples/example_subplots.py#L62
