### ISSUE TITLE
Hi, just a short note for everyone writing loooooooooong ipytho notebooks.

### ISSUE THREAD

**Issue by cqcn1991** [scls19fr/windrose#29]
Forgive me if this is irrelevant, I'm just trying to help with someone like me.

Now I'm trying to make a sidebar of the notebook, because my notebook is rather long.
A short demo:

![toc](https://cloud.githubusercontent.com/assets/2425141/13720167/a7f8a058-e83c-11e5-8e84-4ebda0c660dc.gif)

I have opened an issue at https://github.com/ipython-contrib/IPython-notebook-extensions/issues/532
And, you can try other toc extensions as well.

**Comment by scls19fr** [comment]
Thanks for this contribution. I'm closing this issue as it's more IPython related.
