### ISSUE TITLE
set common radial scale

### ISSUE THREAD

**Issue by slharris** [scls19fr/windrose#34]
I am creating multiple wind roses and I would like them all to be comparable. Is there a way to set a common radial scale?
Any feedback will be greatly appreciated.
Thank you

I am currently using the following:

```python
def new_axes():
                            fig = plt.figure(figsize=(8, 8), dpi=80, facecolor='w', edgecolor='k')
                            rect = [0.1, 0.1, 0.8, 0.8]
                            ax = WindroseAxes(fig, rect, axisbg='w')
                            fig.add_axes(ax)
                            return ax
                        
def set_legend(ax):
                            l = ax.legend(borderaxespad=-0.10, title='knots')
                            plt.setp(l.get_texts(), fontsize=8)
                        
                        
ax = new_axes()
ax.contourf(wd, ws, normed=True, bins=np.arange(0,30,5), opening=0.8, edgecolor='white', cmap=cm.hot)

set_legend(ax)
```

**Comment by scls19fr** [comment]
Hello,

You should have a look at this closed issue
https://github.com/scls19fr/windrose/issues/14

I'm closing this issue but feel free to reopen it in case of problem

Kind regards

PS: Please use backquote for code ! https://help.github.com/articles/creating-and-highlighting-code-blocks/
PS2: All closed issues can be found using https://github.com/scls19fr/windrose/issues?q=is%3Aissue+is%3Aclosed

**Comment by slharris** [comment]
thank you!

On 31 May 2016 at 14:48, scls19fr <notifications@github.com> wrote:

> Hello,
>
> You should have a look at this closed issue
> #14 <https://github.com/scls19fr/windrose/issues/14>
>
> I'm closing this issue but feel free to reopen it in case of problem
>
> Kind regards
>
> PS: Please use backquote for code !
> https://help.github.com/articles/creating-and-highlighting-code-blocks/
> PS2: All closed issues can be found using
> https://github.com/scls19fr/windrose/issues?q=is%3Aissue+is%3Aclosed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scls19fr/windrose/issues/34#issuecomment-222591694>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMVKOFNy0fViS-0zYyk3Ltj3_NbOlSAhks5qG72HgaJpZM4IqFlW>
> .
>



-- 

Dr Sarah Harris
Research Fellow

Earth, Atmosphere and Environment
Monash University
Room 227, 9 Rainforest Walk, Clayton Campus
Wellington Rd
Clayton VIC 3800
Australia

T: +61 3 9902 4243
E: sarah.harris@monash.edu <name.surname@monash.edu>

**Comment by scls19fr** [comment]
My pleasure!
Feel free to contribute to improve windrose (code, doc...)
