### ISSUE TITLE
Request: Register axes to matplotlib, then we can use as "projection="

### ISSUE THREAD

**Issue by brunorpinho** [scls19fr/windrose#38]
First, I would like to thank you for this amazing tool. I am using it to plot geological faults in rose diagrams. 
I would like to give you an an idea to register the axes as projection automatically after we import WindroseAxes.

You just have to do this:

1. First, import register_projection:
`from matplotlib.projections import register_projection`

2. Then add a `name` variable : 
```
class WindroseAxes(PolarAxes):
    name = 'windrose'
    ...
```

3. Finally,  at the end of windrose.py, you add:

`register_projection(WindroseAxes)`

I think this is going to work. If it doesn't, please take a look at these two examples:
[Example 1](http://matplotlib.org/examples/api/custom_projection_example.html)
[Example 2](https://github.com/joferkington/mplstereonet/blob/dc97b59ac46fcf03ac345dee843e1c25c135fd28/mplstereonet/stereonet_axes.py)

Use it as:

```
ax1 = fig.add_subplot(131, projection='polar')
ax2 = fig.add_subplot(132, projection='rectilinear')
ax3 = fig.add_subplot(133, projection='windrose')

ax3.bar(dir, vals)
```

**Comment by scls19fr** [comment]
Hello Bruno,

thanks for this suggestion.
I've just create a PR about it.
See https://github.com/scls19fr/windrose/pull/39

Could you have a look before merging ?

Branch is named `register_axe`
https://github.com/scls19fr/windrose/tree/register_axe

To test just git fork this repository

`git checkout register_axe`

and install

`python setup.py install`


Kind regards

**Comment by brunorpinho** [comment]
Working great!

**Comment by scls19fr** [comment]
Ok so I'm merging !
