### ISSUE TITLE
Change labels in wind rose legend

### ISSUE THREAD

**Issue by jtmcleod1989** [scls19fr/windrose#40]
Hi, is it possible to customize/overwrite the text labels in the wind rose legend? Thanks!

**Comment by brunorpinho** [comment]
Yes, try to overwrite the axes Legend object. Like this:

```
import matplotlib as mpl

ax.legend_ = mpl.legend.Legend(ax, ax.patches_list, ['Text Label 1', Text Label 2'] , 'best')
```

Cheers!

**Comment by scls19fr** [comment]
Thanks @brunorpinho for this prompt answer.
@jtmcleod1989 I close this issue. Feel free to reopen it if it doesn't help.

**Comment by jtmcleod1989** [comment]
Thanks very much, @brunorpinho! That did the trick.
