### ISSUE TITLE
matplotlib 2.0 warning : axisbg -> facecolor

### ISSUE THREAD

**Issue by cqcn1991** [scls19fr/windrose#49]
I was getting 

```
/Users/cqcn1991/anaconda/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
```

when using `windrose` to make simple plots. I think it might the lib's problem, is there anything I can help?

**Comment by scls19fr** [comment]
Hi @cqcn1991 

https://github.com/scls19fr/windrose/search?utf8=%E2%9C%93&q=axisbg
PR are welcome !

Kind regards

**Comment by scls19fr** [comment]
Thanks @cqcn1991 for pointing this issue
Thanks @fmaussion for this PR.
Nice to have active contributors like you.
