### ISSUE TITLE
projection="windrose" not working

### ISSUE THREAD

**Issue by NicWayand** [scls19fr/windrose#53]
I just cloned and installed the most recent github version that should have the projection="windrose" option.

But trying the example code below I get an `ValueError: Unknown projection 'windrose'` error.

Any suggestions on what I may be doing wrong?

```
from matplotlib import pyplot as plt
import windrose
import matplotlib.cm as cm
import numpy as np

ws = np.random.random(500) * 6
wd = np.random.random(500) * 360

fig = plt.figure()
ax = fig.add_subplot(221, projection="windrose")

ax.contourf(wd, ws, bins=np.arange(0, 8, 1), cmap=cm.hot)

ax.legend(bbox_to_anchor=(1.02, 0))
plt.show()
```

**Comment by scls19fr** [comment]
I don't see this issue on my side. Are you sure you uninstalled windrose correctly before installing latest git version ?

![capture d ecran 2017-04-25 a 09 17 56](https://cloud.githubusercontent.com/assets/109167/25372996/25ba3bda-2998-11e7-91d4-ad0750cc43b3.png)

Related issue https://github.com/scls19fr/windrose/issues/38
Pinging @brunorpinho

**Comment by scls19fr** [comment]
uninstall windrose and try to import windrose it should raises `ModuleNotFoundError`
After you can install lastest git version using:

    pip install git+https://github.com/scls19fr/windrose/

**Comment by NicWayand** [comment]
Yes that was it. Was using an old windrose version. Thank you!
